#!/bin/zsh

# git hook to validate commit-msg.
# We use gitmoji : https://gitmoji.carloscuesta.me/
# this hook validates that the first line of the commit message is a valid gitmoji.
#
# the first parameter is the name of the file which contains the commit message

validate_commit_msg() {
    gitmojis=(
        ":art:"
        ":zap:"
        ":fire:"
        ":bug:"
        ":ambulance:"
        ":sparkles:"
        ":pencil:"
        ":rocket:"
        ":lipstick:"
        ":tada:"
        ":white_check_mark:"
        ":lock:"
        ":apple:"
        ":penguin:"
        ":checkered_flag:"
        ":robot:"
        ":green_apple:"
        ":bookmark:"
        ":rotating_light:"
        ":construction:"
        ":green_heart:"
        ":arrow_down:"
        ":arrow_up:"
        ":pushpin:"
        ":construction_worker:"
        ":chart_with_upwards_trend:"
        ":recycle:"
        ":whale:"
        ":heavy_plus_sign:"
        ":heavy_minus_sign:"
        ":wrench:"
        ":globe_with_meridians:"
        ":pencil2:"
        ":poop:"
        ":rewind:"
        ":twisted_rightwards_arrows:"
        ":package:"
        ":alien:"
        ":truck:"
        ":page_facing_up:"
        ":boom:"
        ":bento:"
        ":ok_hand:"
        ":wheelchair:"
        ":bulb:"
        ":beers:"
        ":speech_balloon:"
        ":card_file_box:"
        ":loud_sound:"
        ":mute:"
        ":busts_in_silhouette:"
        ":children_crossing:"
        ":building_contruction:"
        ":iphone:"
        ":clown_face:"
        ":egg:"
        ":see_no_evil:"
        ":camera_flash:"
        ":alembic:"
        ":mag:"
        ":wheel_of_dharma:"
        ":label:"
        ":seedling:"
        ":triangular_flag_on_post:"
        ":goal_net:"
        ":dizzy:"
        ":wastebasket:"
    )

    gitmojis_joined_with_pipes=${(j.|.)gitmojis}

    regex="^($gitmojis_joined_with_pipes) : "

    # validating the regex on the first line of the file
    if $(head -1 $1 | grep -Eq "$regex"); then
        exit 0
    else
        echo "Your commit message does not start with a gitmoji."
        exit 1
    fi
}

validate_commit_msg $1
